name: ARM64 System Diagnostics

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  diagnostics:
    runs-on: ubuntu-24.04-arm
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Install cpu-checker package
      run: |
        sudo apt-get update
        sudo apt-get install -y cpu-checker
        
    - name: Run system diagnostics
      run: |
        echo "=== System Information ==="
        echo "Kernel messages (dmesg):"
        sudo dmesg
        
        echo -e "\n=== CPU Information ==="
        cat /proc/cpuinfo
        
        echo -e "\n=== KVM Support Check ==="
        sudo kvm-ok || echo "KVM check failed or not supported"
        
        echo -e "\n=== Memory Information ==="
        cat /proc/meminfo
        
        echo -e "\n=== Additional System Info ==="
        echo "Architecture: $(uname -m)"
        echo "Kernel version: $(uname -r)"
        echo "OS version: $(lsb_release -a 2>/dev/null || cat /etc/os-release)"
